auction/urls.py
from django.urls import path
from . import views

app_name = "auction"

urlpatterns = [
    path('', views.AllAuctions.as_view(), name="auctions"),
    path('<int:pk>/', views.SingleAuction.as_view(), name="singleAuction"),
    path('add_auction/', views.AddAuction.as_view(), name="addAuction"),
    path('offers/', views.ViewOffers.as_view(), name="offers"),
    path('pay/<int:pk>/', views.Pay.as_view(), name="pay")
]

fire_sale/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls'), name='user'),
    path('', include('auction.urls', namespace="auction")),
    path('manage/', include('administrator.urls'), name="manage")
]

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('profile/', views.UserProfile.as_view(), name="user_profile"),
    path('profile/<int:pk>/', views.Profile.as_view(), name="profile"),
    path('purchases/', views.Purchases.as_view(), name="purchases"),
    path('sales/', views.Sales.as_view(), name="sales"),
    path('my_auctions/', views.MyAuctions.as_view(), name="myAuctions"),
    path('register/', views.Register.as_view(), name="register"),
    path('login/', views.Login.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page="user:login"), name="logout"),
    path('report/', views.Report.as_view(), name="report"),
    path('review/', views.Review.as_view(), name="review")
]

auction/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Condition(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Province(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Location(models.Model):
    postal_code = models.IntegerField(validators=[MinValueValidator(100), MaxValueValidator(999)])
    name = models.CharField(max_length=255)
    prov = models.ForeignKey(Province, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.postal_code) + ' ' + self.name + ' ' + str(self.prov)


class Auction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    price = models.PositiveIntegerField()
    loc = models.ForeignKey(Location, on_delete=models.CASCADE)
    cat = models.ForeignKey(Category, on_delete=models.CASCADE)
    condition = models.ForeignKey(Condition, on_delete=models.CASCADE)
    creation_time = models.DateTimeField(auto_now_add=True)
    is_finished = models.BooleanField(default=False)


class Image(models.Model):
    link = models.CharField(max_length=255)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name='images')


class Offer(models.Model):
    class OfferStatus(models.IntegerChoices):
        PEND = 1, _('Pending')
        COUNT = 2, _('Counter')
        DECL = 3, _('Declined')
        ACC = 4, _('Accepted')
        PAID = 5, _('Paid')

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    price = models.PositiveIntegerField()
    status = models.IntegerField(choices=OfferStatus.choices, validators=[MinValueValidator(1), MaxValueValidator(5)])
    seller_has_reviewed = models.BooleanField(default=False)
    buyer_has_reviewed = models.BooleanField(default=False)
    # auto_now instead of auto_now_add because this should be updated whenever changed
    creation_time = models.DateTimeField(auto_now=True, null=True)

    def get_status(self):
        return self.OfferStatus(self.status).label

    # def get_highest_price(self):
    #     highest_price = self.objects.aggregate(Max('price'))['highest_price']
    #     return self.objects.filter(status=highest_price).first()

auction/forms/add_auction_form.py
from django.forms import ModelForm, widgets, Form
from django import forms
from auction.models import Auction, Location, Category, Condition
from user.models import User


class AddAuctionForm(Form):
    title = forms.CharField(max_length=255, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(max_length=255, required=True, widget=forms.Textarea(attrs={'class': 'form-control'}))
    price = forms.IntegerField(required=True, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    image = forms.CharField(max_length=255, required=True, label="Images (put a space between links)",
                            widget=forms.TextInput(attrs={'class': 'form-control'}))

    loc = forms.ModelChoiceField(required=True, queryset=Location.objects.all())
    cat = forms.ModelChoiceField(required=True, queryset=Category.objects.all())
    condition = forms.ModelChoiceField(required=True, queryset=Condition.objects.all())

auction/forms/make_counter_offer_form.py
from django import forms


class MakeCounterOfferForm(forms.Form):
    price = forms.IntegerField(required=True, widget=forms.NumberInput(attrs={'class': 'form-control'}))

auction/forms/make_offer_form.py
from django import forms


class MakeOfferForm(forms.Form):
    price = forms.IntegerField(required=True, widget=forms.NumberInput(attrs={'class': 'form-control'}))

auction/forms/pay_forms.py
from auction import models
from user import models as user_models
from django import forms


class ContactPayForm(forms.Form):
    first_name = forms.CharField(required=True, max_length=150, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(required=True, max_length=150, widget=forms.TextInput(attrs={'class': 'form-control'}))
    street_name = forms.CharField(required=True, max_length=255,
                                  widget=forms.TextInput(attrs={'class': 'form-control'}))
    house_number = forms.IntegerField(required=True, min_value=0, max_value=9999,
                                      widget=forms.NumberInput(attrs={'class': 'form-control'}))
    city = forms.CharField(required=True, max_length=255, widget=forms.TextInput(attrs={'class': 'form-control'}))
    country = forms.ModelChoiceField(required=True, queryset=user_models.Country.objects.all())
    zip = forms.CharField(required=True, max_length=15, widget=forms.TextInput(attrs={'class': 'form-control'}))


class PaymentPayForm(forms.Form):
    cardholder_first_name = forms.CharField(required=True, max_length=150, label="Cardholders First Name", widget=forms.TextInput(attrs={'class': 'form-control'}))
    cardholder_last_name = forms.CharField(required=True, max_length=150, label="Cardholders Last Name", widget=forms.TextInput(attrs={'class': 'form-control'}))
    card_number = forms.IntegerField(required=True, min_value=1000000000000000, max_value=9999999999999999,
                                     widget=forms.NumberInput(attrs={'class': 'form-control'}))
    expires = forms.DateField(required=False, input_formats=['%Y-%m'], label='Expiry date - (YYYY-MM)',
                              widget=forms.DateInput(attrs={'class': 'form-control'}, format='%Y-%m'))
    cvc = forms.IntegerField(required=True, min_value=100, max_value=999,
                             widget=forms.DateInput(attrs={'class': 'form-control'}))

auction/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import DetailView, ListView
from django.db.models import Q
from . import models
from user import models as user_models
from .forms.add_auction_form import AddAuctionForm
from .forms.make_offer_form import MakeOfferForm
from .forms.pay_forms import ContactPayForm, PaymentPayForm
from .forms.make_counter_offer_form import MakeCounterOfferForm
from django.contrib import messages
from user.notifications import Notification
from django.db.models import Avg

# Create your views here.
from .models import Offer


class AllAuctions(ListView):
    template_name = 'auction/auctions.html'
    model = models.Auction

    def get(self, *args, **kwargs):
        search = self.request.GET.get('search')
        order_by = self.request.GET.get('order_by')
        direction = self.request.GET.get('direction')
        category = self.request.GET.get('category')
        old = self.request.GET.get('old')
        if search and order_by and direction and category and old:
            if search == "*":
                search = ""

            dir_map = {
                'asc': '',
                'desc': '-'
            }
            if order_by == 'price' or order_by == 'title':
                dir_map['asc'] = '-'
                dir_map['desc'] = ''

            direction = dir_map[direction]
            if category == 'all':
                a = models.Auction.objects.filter(title__icontains=search).filter(is_finished=old)
                a = a.union(models.Auction.objects.filter(description__icontains=search).filter(is_finished=old))
            else:
                a = models.Auction.objects.filter(title__icontains=search, cat_id=category).filter(is_finished=old)
                a = a.union(models.Auction.objects
                            .filter(description__icontains=search, cat_id=category).filter(is_finished=old))

            a = a.order_by(str(direction) + str(order_by))
            auctions = [{
                'id': x.id,
                'title': x.title,
                'price': x.price,
                'cat': x.cat.id,
                'loc': x.loc.id,
                'user': x.user.id,
                'first_pic': x.images.first().link,
                'creation_time': x.creation_time
            } for x in a]
            return JsonResponse({"data": auctions})
        else:
            # ignore this warning
            self.object_list = self.get_queryset()
            context = self.get_context_data()
            return self.render_to_response(context)

    def get_queryset(self):
        qs = self.model.objects.exclude(offer__status__in=[4, 5]).order_by('-creation_time')
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        context['categories'] = models.Category.objects.all()
        return context


class SingleAuction(DetailView):
    queryset = models.Auction.objects.all()
    template_name = 'auction/single_auction.html'

    def get_object(self, **kwargs):
        obj = super().get_object()
        return obj

    def get_context_data(self, **kwargs):
        form = MakeOfferForm()
        context = super().get_context_data(**kwargs)
        context['form'] = form
        context['highest_offer'] = models.Offer.objects.filter(auction=self.object).order_by('-price').first()
        accepted_paid = models.Offer.objects.filter(auction=self.object, status__in=[4, 5])
        all_similar_items = models.Auction.objects.filter(cat=self.object.cat, is_finished=False).exclude(id=self.object.id)

        if len(accepted_paid) > 0:
            print("acc off")
            context['accepted_offer'] = accepted_paid[0]

        similar_items = []
        for i, x in enumerate(all_similar_items):
            if i >= 4:
                break
            similar_items.append(x)

        if len(similar_items) > 0:
            context['similar_items'] = similar_items

        return context

    def post(self, request, pk):
        print(request.POST)
        if 'delete_auction' in request.POST:
            auction_id = request.POST['delete_auction']
            auction = models.Auction.objects.get(id=pk)
            if auction.is_finished:
                messages.error(request, 'Cannot delete this auction')
                return redirect('/')

            auction.delete()
            messages.success(request, 'Auction deleted!')
            return redirect('/')

        form = MakeOfferForm(data=request.POST)
        if form.is_valid():
            auction = models.Auction.objects.get(id=pk)
            offer_obj = models.Offer()
            offer_obj.price = form.cleaned_data.get('price')
            offer_obj.auction = auction
            offer_obj.user = request.user
            offer_obj.status = 1
            offer_obj.save()

            messages.success(request, 'Offer sent!')
            # TODO: in notification link filter by auction when/if /offer supports it
            Notification("New Offer!",
                         str(f"You have received a new offer from user '{request.user.username}'"
                             f" on your item '{models.Auction.objects.get(id=pk).title}'. "
                             f"Offered price: {form.cleaned_data.get('price')}"),
                         auction.user,
                         "/offers/?received_offers")

            return redirect(f'/{pk}/')


class AddAuction(LoginRequiredMixin, View):
    def get(self, request):
        form = AddAuctionForm()
        return render(request, 'auction/add_auction.html', {
            'form': form
        })

    def post(self, request):
        form = AddAuctionForm(data=request.POST)
        if form.is_valid():
            auction_obj = models.Auction()
            auction_obj.user = request.user
            auction_obj.title = form.cleaned_data['title']
            auction_obj.description = form.cleaned_data['description']
            auction_obj.price = form.cleaned_data['price']
            auction_obj.loc = form.cleaned_data.get('loc')
            auction_obj.cat = form.cleaned_data.get('cat')
            auction_obj.condition = form.cleaned_data.get('condition')

            auction_obj.save()

            image_list = form.cleaned_data['image'].split()

            for image in image_list:
                image_obj = models.Image()
                image_obj.link = image
                image_obj.auction = auction_obj

                image_obj.save()

            # TAGS DISCONTINUED FOR NOW - NOT IMPORTANT
            # for word in form.cleaned_data['tags'].split(" "):
            # tag_obj = models.Tag()
            # tag_obj.name
            # tag_obj.save()
            return redirect('/')


class ViewOffers(LoginRequiredMixin, ListView):
    template_name = 'auction/offers.html'
    # paginate_by = 100
    model = models.Offer

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(user=self.request.user).exclude(status=5).exclude(status=2).order_by('-creation_time')

    def get_context_data(self, *args):
        context = super().get_context_data()
        context['received_offers'] = models.Offer.objects.all().filter(auction__user=self.request.user) \
            .exclude(status__in=[5, 2])
        q2 = models.Offer.objects.all().filter(user=self.request.user).filter(status=2)

        context['received_offers'] = context['received_offers'].union(q2).order_by('-creation_time')
        return context

    def post(self, request):
        if 'counter_offer_id' in request.POST:  # Counter offer only
            offer_id = request.POST['counter_offer_id']
            offer_price = request.POST['counter_offer_price']

            offer = models.Offer.objects.get(id=offer_id)
            old_offer_price = offer.price

            offer.price = offer_price
            offer.status = 2
            print(offer.auction.title)

            offer.save()
            Notification("Counter Offer!",
                         str(f"You have received a counter offer on the item '{offer.auction.title}'. "
                             f"Your offered price: {old_offer_price}kr. "
                             f"Their counter offer: {offer.price}kr. "),
                         offer.user,
                         "/offers/?received_offers")
            messages.success(request, 'Counter offer sent!')

            return redirect(f'/offers/?received_offers')

        elif 'cancel_offer' in request.POST:  # Cancel offers
            offer_id = request.POST['cancel_offer']
            offer = models.Offer.objects.get(id=offer_id)
            if offer.status == 4 or offer.status == 5:
                messages.error(request, 'Cannot cancel this offer')
                return redirect(f'/offers')

            offer.delete()
            messages.success(request, 'Offer cancelled!')
            return redirect(f'/offers')

        else:  # Accept or decline only
            offer_response = request.POST['offer_response'].split('_')

            offer = models.Offer.objects.get(id=offer_response[1])
            offer.status = offer_response[0]
            offer.auction.is_finished = True

            offer.save()
            if offer_response[0] == str(4):
                print(offer_response[0])
                offers_to_update = Offer.objects.all()
                for offer_to_decline in offers_to_update:
                    if offer_to_decline.id != int(offer_response[1]) and offer_to_decline.auction.id == offer.auction.id:
                        Notification("Offer Declined", str(f"Your offer of {offer_to_decline.price}Kr "
                                                           f"on item '{offer.auction.title}' has been declined."),

templates/auction/add_auction.html
{% extends "base.html" %}
{% block content %}
    <div class="add-auction-center">
        <h1 class="add-auction-title">Add Auction</h1>
        <form class="form-horizontal" id="add-auction-form" action="{% url 'auction:addAuction' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create" class="btn btn-primary pull-right"  style="clear:both; margin: 10px 0">
        </form>
    </div>
{% endblock %}

templates/auction/auctions.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div id="search_container" class="input-group">
        <a href="{% url 'auction:addAuction' %}" class="btn btn-info" role="button">Add Auction</a>
        <input id="search-box" type="search" placeholder="search.." class="form-control" />
        <ul id="orderby_drop">
            <label>Order By</label>
            <select id="order_by_select" class="form-select" aria-label="Order by select">
                <option value="creation_time" selected>Newest &#10033;</option>
                <option value="price">Lowest Price &#9046;</option>
                <option value="title">Alphabet &#127312;</option>
            </select>
        </ul>
        <ul id="direction_drop">
            <label>Direction</label>
            <select id="direction_select" class="form-select" aria-label="Order by select">
                <option value="desc" selected>Descending &#9660;</option>
                <option value="asc">Ascending &nbsp;&nbsp;&#9650;</option>
            </select>
        </ul>
        <div class="input-group-btn">
            <button type="button" id="search-btn" class="btn btn-primary">Search</button>
        </div>
    </div>
    <div id="main_auction_and_category_container" style="display: flex;">
        <div id="auctions_container" style="display: flex; flex-wrap: wrap; width: 70%;">
            {% for auction in object_list %}
                <div class="card">
                    <div class="card-header">
                        <h5 style="font-weight: 400; line-height: 1.2;">{{ auction.title }}</h5>
                    </div>
                    <div style="height: 200px; text-align: center;"><img src="{{ auction.images.first.link }}" class="card-img-middle" alt="..." style="max-height: 100%; max-width: 100%;"></div>
                    <div class="card-body">
                        <h5 class="card-text">{{ auction.price }}<span style="font-size: 15px">Kr.</span></h5>
                        <p> Posted: {{ auction.creation_time|date:'j M, Y - H:i' }}<small style="font-size:15px">{{ auction.creation_time|date:'.s' }}</small></p>
                        <a href="{% url 'auction:singleAuction' pk=auction.id %}" class="btn btn-primary stretched_link">View Auction</a>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div id="category_container" style="width: 30%; margin:10px ;">
            <h1 class="display-6">Categories</h1>
            <ul id="category_list" class="list-group">
                <li class="list-group-item active" data-catid="all">All</li>
                {% for category in  categories%}
                   <li class="list-group-item" aria-current="true" data-catid="{{ category.id }}">&nbsp;&nbsp;&nbsp;{{ category.name }}</li>
                {% endfor %}
            </ul>
            <div class="live-old-buttons">
        <div class="well" id="live-old-buttons">
            <input type="radio" class="form-check-input" name="live_old" id="live" value="False" checked>
            <label class="form-check-label" for="live" >Live auctions </label>
            <br>
            <input type="radio" class="form-check-input" name="live_old" id="old" value="True">
            <label class="form-check-label" for="old" >Old / Finished auctions</label>
        </div>
    </div>
        </div>
    </div>
{% endblock %}

templates/auction/offers.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="offer-sort-buttons">
        <h2 class="user-offers-main-title">View Offers</h2>
        <div class="well">
            <input type="radio" class="btn-check" name="options" id="sent" checked>
            <label class="btn btn-secondary" for="sent" onclick="offers_rb(0)">Sent offers</label>

            <input type="radio" class="btn-check" name="options" id="received" >
            <label class="btn btn-secondary" for="received" onclick="offers_rb(1)">Received offers</label>
        </div>
    </div>
        <div class="offers-sent-offers">
            {% for offer in offer_list %} {# SENT OFFERS #}
                <div class="card">
                    <div class="card-header">
                        <a href="{% url 'auction:singleAuction' pk=offer.auction.id %}">
                            <h5>{{ offer.auction.title }}</h5>
                        </a>
                        <h5>
                            Sent to:
                            <a href="{% url 'user:profile' pk=offer.auction.user_id %}">
                                {{ offer.auction.user }}
                            </a>
                        </h5>
                    </div>
                    <div class="card-body">
                        <img src="{{ offer.auction.images.first.link }}" alt="auction image">
                        <div class="offer-text">
                            <h4> Offer: {{ offer.price }} kr.</h4>
                            <h4> {{ offer.get_status }}</h4>
                        </div>
                        {% if offer.status == 4%}
                            <button class="btn btn-success"
                                    onclick="window.location.href='{% url "auction:pay" pk=offer.id %}'">
                                Pay now
                            </button>
                        {% endif %}
                        {% if offer.status <= 2 %}
                            <form role="form" action="{% url 'auction:offers' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="cancel_offer" value="{{ offer.id }}">
                                <input type="submit" value="Cancel" class="btn btn-danger">
                            </form>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="offers-received-offers">
            {% for offer in received_offers %} {# Received OFFERS #}
                <div class="card">
                    <div class="card-header">
                        <a href="{% url 'auction:singleAuction' pk=offer.auction.id %}">
                            <h5>{{ offer.auction.title }}</h5>
                        </a>

                        {% if offer.status == 2 %}
                            <h5 class="counter_offer_from_user">
                                {{ offer.get_status }} Counter offer from:
                                <a href ="{% url 'user:profile' pk=offer.auction.user_id %}">
                                     {{ offer.auction.user.username }}
                                </a>
                            </h5>
                        {% else %}
                            <h5 class="not_counter_offer_from_user">
                                {{ offer.get_status }} Offer from:
                                <a href ="{% url 'user:profile' pk=offer.auction.user_id %}">
                                     {{ offer.user.username }}
                                </a>
                            </h5>
                        {% endif %}

                    </div>
                    <div class="card-body">
                        <img src="{{ offer.auction.images.first.link }}" alt="auction image">
                        <div class="card-text" id="view_offer_btn">
                            <h4> Offer: {{ offer.price }} kr.</h4>
                        </div>
                        <!-- Make offer button -->


                    {% if offer.status == 1 or offer.status == 2 %}
                            <button type="button" class="btn btn-primary modal_{{ offer.get_status }}"
                                    data-bs-toggle="modal" data-bs-target="#offerModal{{ offer.id }}">
                                View
                            </button>
                            <!-- View offer Modal -->
                            <div class="modal fade" id="offerModal{{ offer.id }}" tabindex="-1" role="dialog"
                                 aria-labelledby="myLargeModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"
                                                    data-bs-toggle="modal" data-bs-target="#offerModal">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                                                <form role="form" action="{% url 'auction:offers' %}" method="post">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="offer_response" value="4_{{ offer.id }}">
                                                    <input type="submit" value="Accept" class="btn btn-success">
                                                </form>
                                                <form role="form" action="{% url 'auction:offers' %}" method="post">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="offer_response" value="3_{{ offer.id }}">
                                                    <input type="submit" value="Decline" class="btn btn-success">
                                                </form>
                                                {%  if offer.status != 2 %}
                                                    <button type="button"
                                                            class="btn btn-primary button_counter_{{ offer.status }}"
                                                            data-bs-toggle="modal"
                                                            data-bs-target="#counterOfferModal{{ offer.id }}">
                                                        Make counter offer
                                                    </button>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                        {% if offer.status != 2 %}
                            <div class="modal fade" id="counterOfferModal{{ offer.id }}" tabindex="-1" role="dialog"
                                 aria-labelledby="myLargeModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"
                                                    data-bs-toggle="modal" data-bs-target="#CounterOfferModal">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                                                <form role="form" action="{% url 'auction:offers' %}" method="post">
                                                    {% csrf_token %}
                                                    <input name="counter_offer_price" type="number" >
                                                    <input type="hidden" name="counter_offer_id" value="{{ offer.id }}">
                                                    <input type="submit" value="Send" class="btn btn-success">
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    <script src="{% static 'js/offers.js' %}"></script>
{% endblock %}