auction/urls.py
from django.urls import path
from . import views

app_name = "auction"

urlpatterns = [
    path('', views.AllAuctions.as_view(), name="auctions"),
    path('<int:pk>/', views.SingleAuction.as_view(), name="singleAuction"),
    path('add_auction/', views.AddAuction.as_view(), name="addAuction"),
    path('offers/', views.ViewOffers.as_view(), name="offers"),
    path('pay/<int:pk>/', views.Pay.as_view(), name="pay")
]

fire_sale/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls'), name='user'),
    path('', include('auction.urls', namespace="auction")),
    path('manage/', include('administrator.urls'), name="manage")
]

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('profile/', views.UserProfile.as_view(), name="user_profile"),
    path('profile/<int:pk>/', views.Profile.as_view(), name="profile"),
    path('purchases/', views.Purchases.as_view(), name="purchases"),
    path('sales/', views.Sales.as_view(), name="sales"),
    path('my_auctions/', views.MyAuctions.as_view(), name="myAuctions"),
    path('register/', views.Register.as_view(), name="register"),
    path('login/', views.Login.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page="user:login"), name="logout"),
    path('report/', views.Report.as_view(), name="report"),
    path('review/', views.Review.as_view(), name="review")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fire Sale!</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    {% include 'navbar.html' %}
    <main>
        {% include 'messages.html' %}
        {% block content %}
        {% endblock %}
    </main>
    <footer class="footer-bs">
        <div class="card wrapper">
            <div class="card-body">
                <span style="font-weight:100; font-size:8px">&copy; <span id="year"></span>  Helgi Steinarr, Ingólfur &amp; Ríkharður Aron</span>
            </div>
        </div>
        <div class="footer"></div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'js/auctions.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/profile.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/add_auction.js'%}"></script>
        <script type="text/javascript" src="{% static 'js/pay.js'%}"></script>

        <script type="text/javascript">
            function getYear() {
                document.getElementById("year").innerHTML = new Date().getFullYear();
            }
            window.onload = getYear;
        </script>
</body>
</html>

templates/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-default fixed-top navbar-dark" style="background-color: #3c3d41;" id="mainNav">
      <div class="container">
          <a class="navbar-brand" href="/" style="color:white; font-size: 160%;">Fire Sale!</a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#notificationNavbar #profileNavbarDropdown #signinNavbar #navbar-rating" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation" style="float: right;">
            <span class="navbar-toggler-icon"></span>
          </button>

          {% if request.user.is_authenticated %}
          <div style="float: right; margin-left: 40%">
              <div class="collapse navbar-collapse" id="notificationNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <span class="badge badge-pill badge-warning" style="float:right;margin-bottom:-15px;margin-right:-12px;font-size:10px">{{ request.user.notifications.all|length }}</span>
                        <a class="nav-link dropdown-toggle" href="" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Notifications</a>
                        <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="navbarDarkDropdownMenuLink">
                          {% for n in request.user.notifications.all %}
                            <li id="each-noti-container" style="display: block; position: relative; left: 10px; padding-right: 30px;"><a class="dropdown-item" href="{{ n.onclick_link }}">{{ n.title }} <br/> {{ n.text }}</a></li>
                          {% endfor %}
                        </ul>
                    </li>
                </ul>
              </div>
          </div>
          {% endif %}

          <div>
              <div class="collapse navbar-collapse" id="navbar-rating">
                  <ul class="navbar-nav">
                      <li class="nav-item">
                          <a class="nav-link disabled"><span style="font-size:10px">Avg Rating: </span>{{ request.user.profile.rating }}</a>
                      </li>
                  </ul>
              </div>
          </div>

          <div style="float:right; margin-right: 20px; margin-left: 15px;">
          {% if request.user.is_authenticated %}
              <div class="collapse navbar-collapse" id="profileNavbarDropdown">
                  <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          {% if not request.user.profile.profile_picture %}
                              <img class="navbar-user-profile-pic" src="https://www.cmcaindia.org/wp-content/uploads/2015/11/default-profile-picture-gmail-2.png">
                          {% else %}
                              <img class="navbar-user-profile-pic" src="{{ request.user.profile.profile_picture }}">
                          {% endif %}
                          {{ request.user.username }}
                      </a>
                      <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                          <li><a class="dropdown-item" href="{% url 'user:user_profile' %}">Profile</a></li>
                          <li><a class="dropdown-item" href="{% url 'auction:offers' %}">Offers</a></li>
                          <li><a class="dropdown-item" href="{% url 'user:myAuctions' %}">My Auctions</a></li>
                          <li><a class="dropdown-item" href="{% url 'user:sales' %}">Sales</a></li>
                          <li><a class="dropdown-item" href="{% url 'user:purchases' %}">Purchases</a></li>
                          {% if request.user.is_superuser %}
                              <li><a class="dropdown-item" href="#">Manage</a></li>
                          {% endif %}
                          <li><a class="dropdown-item" href="{% url 'user:logout' %}">Log Out</a></li>
                          <li><a class="dropdown-item" href="{% url 'user:report' %}">Report</a></li>
                      </ul>
                    </li>
                  </ul>
              </div>
          {% else %}
              <div class="collapse navbar-collapse" id="signinNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{% url 'user:login' %}" class="nav-item nav-link" id="sign-in-btn">Log In</a>
                    </li>
                </ul>
              </div>
          {% endif %}
          </div>
      </div>
    </nav>