auction/urls.py
from django.urls import path
from . import views

app_name = "auction"

urlpatterns = [
    path('', views.AllAuctions.as_view(), name="auctions"),
    path('<int:pk>/', views.SingleAuction.as_view(), name="singleAuction"),
    path('add_auction/', views.AddAuction.as_view(), name="addAuction"),
    path('offers/', views.ViewOffers.as_view(), name="offers"),
    path('pay/<int:pk>/', views.Pay.as_view(), name="pay")
]

fire_sale/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls'), name='user'),
    path('', include('auction.urls', namespace="auction")),
    path('manage/', include('administrator.urls'), name="manage")
]

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('profile/', views.UserProfile.as_view(), name="user_profile"),
    path('profile/<int:pk>/', views.Profile.as_view(), name="profile"),
    path('purchases/', views.Purchases.as_view(), name="purchases"),
    path('sales/', views.Sales.as_view(), name="sales"),
    path('my_auctions/', views.MyAuctions.as_view(), name="myAuctions"),
    path('register/', views.Register.as_view(), name="register"),
    path('login/', views.Login.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page="user:login"), name="logout"),
    path('report/', views.Report.as_view(), name="report"),
    path('review/', views.Review.as_view(), name="review")
]

user/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import ForeignKey

User = get_user_model()
from django.utils.translation import gettext_lazy as _
from auction import models as auction_models

# Create your models here.
""" REPLACED BY AUTH_USER BUILT INTO DJANGO
class User(models.Model):
    name = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    birthday = models.DateField()
    is_admin = models.BooleanField()

    def __str__(self):
        return self.name
"""


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    profile_picture = models.CharField(max_length=999, null=True)
    birthday = models.DateField(null=True)
    bio = models.CharField(max_length=255, null=True)
    # 0-10, 0 = 0 star, 5 = 2.5 star, 10 = 5 star
    rating = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(10)])


class Report(models.Model):
    class ReportsTypes(models.IntegerChoices):
        USER = 1, _("user")
        BUG = 2, _("bug")
    reported_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reports_against', default=None,
                                      null=True)
    reporter_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reports_made')
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    report_type = models.PositiveIntegerField(choices=ReportsTypes.choices,
                                              validators=[MinValueValidator(1), MaxValueValidator(2)])


class Review(models.Model):
    class ReviewType(models.IntegerChoices):
        SALE = 1, _('sale')
        PURCHASE = 2, _('purchase')

    reviewed_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reviews_against')
    reviewer_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reviews_made')
    description = models.CharField(max_length=255)
    rating = models.PositiveIntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)])
    type = models.PositiveIntegerField(choices=ReviewType.choices,
                                       validators=[MinValueValidator(1), MaxValueValidator(2)])
    offer = models.ForeignKey(auction_models.Offer, on_delete=models.CASCADE, related_name='offer_reviews')


class Country(models.Model):
    code = models.CharField(max_length=2)
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class CardInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="cards")
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    cardholder_first_name = models.CharField(max_length=255)
    cardholder_last_name = models.CharField(max_length=255)
    card_number = models.BigIntegerField(validators=[MinValueValidator(1000000000000000),
                                                     MaxValueValidator(9999999999999999)])
    cvc = models.SmallIntegerField(validators=[MinValueValidator(100), MaxValueValidator(999)])
    expires = models.DateField()
    street = models.CharField(max_length=255)
    house_number = models.PositiveIntegerField(validators=[MinValueValidator(0), MaxValueValidator(9999)], default=0)
    city = models.CharField(max_length=255)
    zip = models.CharField(max_length=15)
    country = ForeignKey(Country, on_delete=models.CASCADE, related_name="cards")


class Notification(models.Model):
    title = models.CharField(max_length=100)
    text = models.CharField(max_length=255)
    time_created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="notifications")
    onclick_link = models.CharField(max_length=255)
    read = models.BooleanField(default=False)

    class Meta:
        ordering = ['-time_created']

user/forms/EditUserForm.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.validators import EmailValidator

User = get_user_model()


class EditUserForm(forms.Form):
    def __init__(self, username, *args, **kwargs):
        self.username = username
        super(EditUserForm, self).__init__(*args, **kwargs)

    first_name = forms.CharField(max_length=150, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=150, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(max_length=254, label='email', required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}),
                             validators=[EmailValidator])
    profile_picture = forms.URLField(required=False, max_length=999,
                                     widget=forms.URLInput(attrs={'class': 'form-control'}))
    bio = forms.CharField(max_length=255, required=False, widget=forms.Textarea(attrs={'class': 'form-control'}))
    birthday = forms.DateField(required=False, label="Birthday (YYYY-MM-DD)", input_formats=['%Y-%m-%d'],
                               widget=forms.DateInput(attrs={'class': 'form-control'}, format='%Y-%m-%d'))

    def clean(self):
        c = super().clean()
        try:
            email = c['email']
        except KeyError:
            return
        new = User.objects.filter(email=email)
        if new.count():
            if new[0].username != self.username:
                raise forms.ValidationError({'email': "A user with this email already exist"})

user/forms/ReviewForm.py
from django import forms


class ReviewForm(forms.Form):
    rating = forms.IntegerField(min_value=0, max_value=10, widget=forms.NumberInput)
    description = forms.CharField(max_length=255, widget=forms.Textarea)

user/forms/UserCreateForm.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from django.utils.safestring import mark_safe

User = get_user_model()


class UserCreateForm(UserCreationForm, forms.Form):
    email = forms.EmailField(max_length=254, label=mark_safe('Email'), required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=150, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=150, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name")

    def clean(self):
        super().clean()
        try:
            email = self.cleaned_data['email'].lower()
        except KeyError:
            return
        new = User.objects.filter(email=email)
        if new.count():
            raise forms.ValidationError("A user with this email already exist")

user/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views import View
from django.views.generic import DetailView, ListView, FormView
from user.forms.UserCreateForm import UserCreateForm
from user.forms.EditUserForm import EditUserForm
from user import models
from auction import models as auction_models
from user.forms.ReviewForm import ReviewForm
from django.db.models import Avg

User = get_user_model()


# Create your views here.
class UserProfile(LoginRequiredMixin, View):
    def get(self, request):
        return redirect(f'/profile/{request.user.id}')


class Profile(LoginRequiredMixin, DetailView):
    queryset = User.objects.all()
    template_name = 'user/profile.html'

    def get_object(self, **kwargs):
        obj = super().get_object()
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['payment_options'] = None
        context['edit_user_form'] = None
        context['reviews'] = models.Review.objects.filter(reviewed_user=self.object.id)

        if self.request.user == self.object:
            context['payment_options'] = self.object.cards
            context['edit_user_form'] = EditUserForm(self.request.user.username,
                                                     data={"username": self.request.user.username,
                                                           "first_name": self.request.user.first_name,
                                                           "last_name": self.request.user.last_name,
                                                           "email": self.request.user.email,
                                                           "profile_picture": self.request.user.profile.profile_picture,
                                                           "bio": self.request.user.profile.bio,
                                                           "birthday": self.request.user.profile.birthday})
        return context

    def post(self, request, *args, **kwargs):
        print(request.POST)
        if 'first_name' in request.POST:
            form = EditUserForm(self.request.user.username, data=request.POST)

            if form.is_valid():
                user_model_instance = User.objects.get(id=request.user.id)
                user_model_instance.first_name = form.cleaned_data['first_name']
                user_model_instance.last_name = form.cleaned_data['last_name']
                user_model_instance.email = form.cleaned_data['email']
                user_model_instance.profile.bio = form.cleaned_data['bio']
                user_model_instance.profile.profile_picture = form.cleaned_data['profile_picture']
                user_model_instance.profile.birthday = form.cleaned_data['birthday']
                user_model_instance.save()
                user_model_instance.profile.save()
                messages.success(request, 'Profile Successfully Updated')
                return redirect(f"/profile/{request.user.id}?profile_info")
            else:
                for error in form.errors:
                    print(error)
                messages.error(request, form.errors, extra_tags='edit_form_msg_li')
                return redirect(f"/profile/{request.user.id}?profile_edit")
        elif 'delete_account' in request.POST:
            print("Delete")
            account_id = request.POST['delete_account']
            account = models.User.objects.get(id=request.user.id)

            account.delete()
            messages.success(request, 'Bye!')
            return redirect('/')



class Register(View):
    def get(self, request):
        return render(request, 'user/register.html', {
            'form': UserCreateForm()
        })

    def post(self, request):
        form = UserCreateForm(data=request.POST)
        if form.is_valid():
            form.save()
            print(request.POST)
            profile = models.Profile()
            profile.user = User.objects.get(username=request.POST.get('username'))
            profile.save()
            messages.success(request, 'Account created successfully')
            return redirect('/login/')
        else:
            # messages.error(request, 'invalid registration details')
            return render(request, 'user/register.html', {
                'form': UserCreateForm(data=request.POST)
            })


class Login(LoginView):
    template_name = "user/login.html"
    redirect_authenticated_user = True


class Report(View):
    pass


class MyAuctions(LoginRequiredMixin, ListView):
    model = auction_models.Auction
    template_name = 'user/my_auctions.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(user__id=self.request.user.id).order_by('-creation_time')


class Sales(LoginRequiredMixin, ListView):
    model = auction_models.Offer
    template_name = 'user/sales.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(auction__user_id=self.request.user.id).filter(status__in=[4, 5]).order_by('-creation_time')


class Purchases(LoginRequiredMixin, ListView):
    model = auction_models.Offer
    template_name = 'user/purchases.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(user_id=self.request.user.id, status__in=[4, 5]).order_by('-creation_time')


class Review(LoginRequiredMixin, FormView):
    template_name = 'user/review.html'
    form_class = ReviewForm
    success_url = '/'

    def get(self, request, *args, **kwargs):
        if request.GET.get('reviewing') and request.GET.get('offer_id') and \
                self.valid_review(request.GET.get('reviewing'), request.GET.get('offer_id')):
            return super().get(request, *args, **kwargs)

        messages.error(request, "Invalid request - Contact admin if this problem persists")
        # Trick to go back and keep scroll position,
        # I could go back with HTTP_REFERER, but that would not keep scroll position
        return HttpResponse('<script>history.back();</script>')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        offer = auction_models.Offer.objects.get(id=self.request.GET.get('offer_id'))
        if self.request.GET.get('reviewing') == 'buyer':
            context['reviewed_user'] = offer.user
        else:  # reviewing seller
            context['reviewed_user'] = offer.auction.user
        context['offer_id'] = offer.id
        context['reviewing'] = self.request.GET.get('reviewing')
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            offer = auction_models.Offer.objects.get(id=self.request.GET.get('offer_id'))
            new_review = models.Review()
            new_review.description = form.cleaned_data['description']
            new_review.rating = form.cleaned_data['rating']
            new_review.offer = offer

            if self.request.GET.get('reviewing') == 'buyer':
                offer.seller_has_reviewed = True
                offer.save()

                new_review.type = 1
                new_review.reviewed_user = offer.user
                new_review.reviewer_user = offer.auction.user
                new_review.save()
                calculate_rating(offer.user)
            else:
                offer.buyer_has_reviewed = True
                offer.save()

                new_review.type = 2
                new_review.reviewed_user = offer.auction.user
                new_review.reviewer_user = offer.user
                new_review.save()
                calculate_rating(offer.auction.user)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.INFO, 'Review Sent!')
        return str(self.success_url)

    def valid_review(self, reviewing: str, offer_id: str) -> bool:
        offer = auction_models.Offer.objects.filter(id=offer_id)
        if len(offer) == 0:
            return False
        offer = offer[0]
        if reviewing == 'buyer':
            if offer.status != 5 and offer.status != 4:
                return False
            else:
                if offer.seller_has_reviewed:
                    return False
            return True
        elif reviewing == 'seller':
            if offer.status != 5:
                return False
            else:
                if offer.buyer_has_reviewed:
                    return False
            return True
        else:
            return False

def calculate_rating(user):
    """
        Recalculates and updates the average rating of the user
        :param user:
    """
    reviews = models.Review.objects.filter(reviewed_user=user)
    rating = 0
    for review in reviews:
        rating += review.rating
    user.profile.rating = int(rating / len(reviews))
    user.profile.save()

templates/user/login.html
{% extends 'base.html' %}
{% block content%}
    <div class="login-center">
    <h1 class="login-Title">Login</h1>
    <form class="form form-horizontal" action="{% url 'user:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Login" class="btn btn-primary pull-right">
    </form>
    <a id="signup-btn" href="{% url 'user:register' %}" class="btn">Sign up</a>
    </div>
{% endblock %}

templates/user/my_auctions.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1>My Auctions</h1>
    {% if object_list|length < 1 %}
        <h3>No auctions listed!</h3>
    {% endif %}
    {% for auction in object_list %}
         <div class="card" style="margin: 10px;">
            <div class="card-header">
                <h5 style="font-weight: 400; line-height: 1.2;">{{ auction.title }}</h5>
            </div>
            <div style="height: 200px; text-align: center;"><img src="{{ auction.images.first.link }}" class="card-img-middle" alt="..." style="max-height: 100%; max-width: 100%;"></div>
            <div class="card-body">
                <h5 class="card-text">{{ auction.price }}<span style="font-size: 15px">Kr.</span></h5>
                <p> Posted: {{ auction.creation_time|date:'j M, Y - H:i' }}<small style="font-size:15px">{{ auction.creation_time|date:'.s' }}</small></p>
                <a href="{% url 'auction:singleAuction' pk=auction.id %}" class="btn btn-primary stretched_link">View Auction</a>
                <a href="{% url 'auction:offers' %}?received_offers" class="btn btn-info stretched_link">See offers</a> <!-- TODO: if filter by auction in offers screeen is implemented make this filter by this auction -->
            </div>
         </div>
    {% endfor %}
{% endblock %}

templates/user/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="profile_container">
        <div class="sidenav">
            <a href="./?profile_info">Profile</a>
            {% if request.user.username == user.username %}
                <a href="./?profile_edit">Edit Info</a>
                <a href="./?payment_options">Payment Options</a>
            {% endif %}
            <a href="./?profile_reviews">See reviews</a>
            {% if request.user.username == user.username %}
                <br><br><br>
                <form role="form" action="/profile/{{ request.user.id }}/" method="post" style="padding-left: 40px">
                        {% csrf_token %}
                        <input type="hidden" name="delete_account" value="{{ account.id }}">
                        <input type="submit" value="Delete Account" class="btn btn-danger">
                    </form>
            {% else %}
                {% if request.user.is_superuser %}
                    <a id="user-profile-ban-user" href="#" class="text-danger">Ban User</a>
                    <a id="user-profile-ban-user" href="#" class="text-danger">Make Admin</a>
                {% endif %}
            {% endif %}

        </div>

        <div id="profile_main_page" class="main_page">
            <span id="profile_message" style="display: none;"></span>
            {% include 'user/profile_info.html' %}
            {% include 'user/profile_reviews.html' %}
            {% if edit_user_form != None and payment_options != None %}
                {% include 'user/profile_edit.html' %}
                {% include 'user/profile_payment_options.html' %}
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/user/profile_edit.html
<div id="profile_edit">
    <form method="post" action="{% url 'user:profile' pk=request.user.id %}" name="profile_edit" class="form form-horizontal">
        {% csrf_token %}
        {{ edit_user_form }}
        <input type="submit" value="Update" class="btn btn-primary pull-right">
    </form>
</div>

templates/user/profile_info.html
<div id="profile_info">
    <div class="user-profile-info card">
        <div id="img_username_container">
            {% if not user.profile.profile_picture %}
                <img id="user-profile-picture" src="https://www.cmcaindia.org/wp-content/uploads/2015/11/default-profile-picture-gmail-2.png">
            {% else %}
                <img id="user-profile-picture" src="{{ user.profile.profile_picture }}">
            {% endif %}
            <a id="user-profile-username">{{ user.username }}</a>
        </div>
        <div id="profile_lower_container">
            <div class="user-profile-small-info">
                <a><b>{{ user.first_name }} {{ user.last_name }}</b></a>
                <label>Rating</label>
                <a>{{ user.profile.rating }}/10</a>
                <label>Joined</label>
                <a id="user-profile-joined">{{ user.date_joined|date:'j M, Y - H:i' }}<small style="font-size:15px">{{ user.date_joined|date:'.s' }}</small></a>
                <label>Email</label>
                <a id="user-profile-email">{{ user.email }}</a>
                <label>Birthday</label>
                {% if not user.profile.birthday %}
                    <a id="user-profile-born">Unknown</a>
                {% else %}
                    <a id="user-profile-born">{{ user.profile.birthday }}</a>
                {% endif %}
            </div>
            <div id="profile_bio">
                {% if user.profile.bio %}
                    <label><b>Bio</b></label>
                    <p>{{ user.profile.bio }}</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

templates/user/profile_payment_options.html
<div id="profile_payment_options">
    <h1>Your saved payment options</h1>
    <p>Saved payment options already sent to template. access like this: for option in payment_options </p>
    {% for option in payment_options.all %}
        <div class="card">
            <div class="card-body">
                <p>CONTACT NAME: {{ option.first_name }} {{ option.last_name }}</p>
                <p>CARD_NR: {{ option.card_number }}</p>
                <p>CVC: {{ option.cvc }} &nbsp;&nbsp; EXP: {{ option.expires }}</p>
                <p>STREET: {{ option.street }} {{ option.house_number }} &nbsp;&nbsp;CITY: {{ option.city }}</p>
                <p>COUNTRY: {{ option.country.name }}</p>
                <p>CARDHOLDER: {{ option.cardholder_first_name }} {{ option.cardholder_last_name }}</p>
            </div>

        </div>

    {% endfor %}
</div>

templates/user/profile_reviews.html
<div id="profile_reviews">
    {% for review in reviews %}
        <div class="card">
            <div class="card-body">
                <span>From: {{ review.reviewer_user.username }}</span><br>
                <span>Rating: {{ review.rating }}/10</span><br>
                <span>Review: {{ review.description }}</span><br>
                <span>Item: {{ review.offer.auction.title }}</span>
            </div>
        </div>
    {% endfor %}
</div>

templates/user/purchases.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1>Purchases</h1>
    <p>Auctions you have won</p>
    {% if object_list|length < 1 %}
        <h3>No Purchases!</h3>
    {% endif %}
    {% for offer in object_list %}
         <div class="card" style="margin: 10px;">
            <div class="card-header">
                <span style="font-weight: 400; line-height: 1.2; font-size: 1.25rem">
                    {{ offer.auction.title }}
                    {% if offer.status == 4 %}
                        <b style="color: yellow; text-shadow: 0px 0px 1px black">Unpaid - Please pay now</b>
                    {% elif offer.status == 5 %}
                        <b style="color: green;">Paid!</b>
                    {% endif %}
                </span>
            </div>
            <div style="height: 200px; text-align: center;"><img src="{{ offer.auction.images.first.link }}" class="card-img-middle" alt="..." style="max-height: 100%; max-width: 100%;"></div>
            <div class="card-body">
                <h5 class="card-text">{% if offer.status == 5%}Paid price: {% endif %}{% if offer.status == 4%}Accepted price: {% endif %}{{ offer.price }}<span style="font-size: 15px">Kr.</span></h5>
                <p> Posted: {{ offer.auction.creation_time|date:'j M, Y - H:i' }}<small style="font-size:15px">{{ offer.auction.creation_time|date:'.s' }}</small></p>
                <a href="{% url 'auction:singleAuction' pk=offer.auction.id %}" class="btn btn-primary stretched_link">View Auction</a>
                {% if offer.status == 4 %}
                    <a href="{% url 'auction:pay' pk=offer.id %}" class="btn btn-success stretched_link">Pay</a>
                {% elif offer.status == 5 %}
                    <button id="buyer_review_button" type="button" class="btn btn-info stretched_link"{% if offer.buyer_has_reviewed %} disabled {% endif %}>
                        <a style="text-decoration: none; color: black;" href="/review/?reviewing=seller&offer_id={{offer.id}}">
                           Review Seller
                        </a>
                    </button>
                    {% if offer.buyer_has_reviewed %}
                        <label for="buyer_review_button" style="color: lightgrey">You have already sent a review</label>
                    {% endif %}
                {% endif %}
            </div>
         </div>
    {% endfor %}
{% endblock %}

templates/user/register.html
{% extends "base.html" %}
{% block content %}
    <div class="register-center">
    <h1 id="register-title">Register</h1>
    <form class="form form-horizontal" action="{% url 'user:register' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Register" class="btn btn-primary pull-right">
    </form>
    </div>
{% endblock %}

templates/user/review.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="review-container">
    <h3 id="review_form_title">Reviewing user: <a href="/profile/{{reviewed_user.id}}" id="review_username">{{ reviewed_user.username }}</a></h3>
    <form method="post" action="/review/?reviewing={{reviewing}}&offer_id={{offer_id}}">
        {% csrf_token %}
        {{ form }}
        <input type="hidden" name="reviewing" value="{{reviewing}}" />
        <input type="hidden" name="offer" value="{{offer}}"/>
        <button type="submit">Submit Review</button>
    </form>
</div>
{% endblock %}

templates/user/sales.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1>My Sales</h1>
    <p>Items you have sold that either only have an accepted offer or are fully paid</p>
    {% if object_list|length < 1 %}
        <h3>No items sold!</h3>
    {% endif %}
    {% for offer in object_list %}
         <div class="card">
            <div class="card-header">
                <h5 style="font-weight: 400; line-height: 1.2;">
                    {{ offer.auction.title }} -
                    {% if offer.status == 4 %}
                        <b style="color: yellow; text-shadow: 0 0 1px black">Buyer has not yet paid</b>
                    {% elif offer.status == 5 %}
                        <b style="color: green;">Buyer has paid!</b>
                    {% endif %}
                </h5>
            </div>
            <div style="height: 200px; text-align: center;"><img src="{{ offer.auction.images.first.link }}" class="card-img-middle" alt="..." style="max-height: 100%; max-width: 100%;"></div>
            <div class="card-body">
                <h5 class="card-text">Accepted Price: {{ offer.price }}<span style="font-size: 15px">Kr.</span></h5>
                <p> Posted: {{ offer.auction.creation_time|date:'j M, Y - H:i' }}<small style="font-size:15px">{{ offer.auction.creation_time|date:'.s' }}</small></p>
                <a href="{% url 'auction:singleAuction' pk=offer.auction.id %}" class="btn btn-primary stretched_link">View Auction</a>

                <button id="buyer_review_button" type="button" class="btn btn-info stretched_link"{% if offer.seller_has_reviewed %} disabled {% endif %}>
                    <a style="text-decoration: none; color: black;" href="/review/?reviewing=buyer&offer_id={{offer.id}}">
                       Review Buyer
                    </a>
                </button>
                {% if offer.seller_has_reviewed %}
                    <label for="buyer_review_button" style="color: lightgrey">You have already sent a review</label>
                {% endif %}

            </div>
         </div>
    {% endfor %}
{% endblock %}